name: AX5-libwrt

on:
  workflow_dispatch:
  workflow_call:
  # schedule:
  #   - cron: "0 20 * * *"

permissions:
  contents: write
  actions: write

jobs:
  Build:
    uses: ./.github/workflows/Buil-OpenWrt.yml
    permissions:
      contents: write
      actions: write
    with:
      repo_url: https://github.com/LiBwrt/openwrt-6.x.git
      repo_branch: main-nss
      config_file: configs/AX5.config
      firmware_tag: AX5
      kernel_file: kernel-6.12
      artifact_prefix: IPQ60XX
      manifest_file: libwrt-qualcommax-ipq60xx.manifest
      release_summary: >-
        这是开启全功能NSS的6.12内核
        # 默认主题: Argon
        # IRQ: 自动调优 (RPS+RFS)
        # NSS-DP: PHY 禁止过度管理 (防抖动)
        # 科学上网: HomeProxy (Sing-Box 内核)
        # 网络: PPPoE IPv4 + IPv6 双栈 + 防火墙优化
        # 上游同步: 自动兼容上游 NSS 内核更新。
